config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#show', via: :get

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]

  resource :dashboard, only: [:show]

  resources :questions do
    post 'finish' => 'questions#finish'
    resources :answers, only: [:create, :edit, :update, :destroy]
  end

  resources :assessments, only: [:new, :create, :show] do
    get 'add_questions'
    put 'assign_questions'
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  has_many :answers, dependent: :destroy

  has_and_belongs_to_many :assessments

  validates_presence_of :prompt

  def has_correct_answer?
    self.answers.pluck(:correct).include?(true)
  end

  def answer_count
    answers.count
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :require_login

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to question_path(@question)
    else
      flash[:errors] = @question.errors.full_messages
      render :new
    end
  end

  def show
    flash[:errors] = nil
    @question = Question.find_by(id: params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
    @question = Question.find_by(id: params[:id])
    @question.destroy
    redirect_to dashboard_path
  end 

  # submits a question for approval from draft
  def finish
    # TODO: extract to service object when this gets bigger.  
    # TODO: extract questions model finish as a concern
    @question = Question.find_by(id: params[:question_id])
    if @question.has_correct_answer?
      flash[:success] = "Question saved successfully!"
      redirect_to dashboard_path
    else
      # flash[:errors] = ["No correct answer selected.  Try again."]
      render :show
    end
  end

  private

  def question_params
    params.require(:question).permit(:prompt)
  end
end

app/views/questions/new.html.erb
<h1>Create question:</h1>

<%= render partial: "shared/errors" %>

<%= form_for @question do |f| %>
  <div class="form-group">
    <%= f.label :prompt, class: "form-label" %>
    <%= f.text_area :prompt, class: "form-control", placeholder: "Who is the president of France?" %>
  </div>

  <%= f.submit "Create", class: "btn btn-success" %>
<% end %>

app/views/questions/show.html.erb
<div class='question-header'>
  <h2 class='question-prompt'><%= @question.prompt %></h2>
  <span class='pull-right'>
    <%= link_to question_path(@question), method: :delete do %>
      <span class='fa fa-remove fa-2x nomark'></span>
    <% end %>
  </span>
</div>

<ul id="questions-list" class="list-group">
  <%= render @question.answers %>
</ul>

<div id="questions-error"></div>

<div class='new-answer'><%= render partial: 'answers/new', locals: { question: @question } %></div>

<!-- TODO: Enable and disable this button based on submission status -->
<%= button_to "Finalize question", question_finish_path(@question), class: 'btn btn-success' %>