config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#show', via: :get

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]

  resource :dashboard, only: [:show]

  resources :questions do
    post 'finish' => 'questions#finish'
    resources :answers, only: [:create, :edit, :update, :destroy]
  end

  resources :assessments, only: [:new, :create, :show] do
    get 'add_questions'
    put 'assign_questions'
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  has_and_belongs_to_many :questions

  validates_presence_of :title, :creator
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  def new
    @assessment = Assessment.new
  end

  def create
    @assessment = current_user.assessments.new(assessment_params)
    if @assessment.save
      redirect_to assessment_add_questions_path(@assessment)
    else
      flash[:errors] = @assessment.errors.full_messages
      render :new
    end
  end

  def show
    @assessment = find_assessment
  end

  def add_questions
    @assessment = find_assessment
  end

  def assign_questions
    @assessment = find_assessment
    if @assessment.update_attributes(assessment_params)
      redirect_to assessment_path(@assessment)
    else
      redirect_to :back
    end
  end

  private

  def find_assessment
    Assessment.find_by(id: params[:assessment_id]) || Assessment.find_by(id: params[:id])
  end

  def assessment_params
    params.require(:assessment).permit(:title, question_ids:[])
  end
end

app/views/assessments/_questions.html.erb
<%= form_for @assessment, url: assessment_assign_questions_path(@assessment), method: :put do |f| %>
  <%= f.collection_check_boxes :question_ids, current_user.questions, :id, :prompt do |question| %>
    <div class="questions-to-assessment-show checkbox checkbox-success">
      <%= question.check_box %>
      <%= question.label %>
    </div>
  <% end %>
  <%= f.submit "Assign Questions", class: "btn btn-success" %>
<% end %>

app/views/assessments/add_questions.html.erb
<h1><%= @assessment.title %></h1>

<%= render partial: 'questions' %>

app/views/assessments/new.html.erb
<h1>Create assessment:</h1>

<%= render partial: "shared/errors" %>

<%= form_for @assessment do |f| %>
  <div class="form-group">
    <%= f.label :title, class: "form-label" %>
    <%= f.text_field :title, class: "form-control", placeholder: "Spring 2016 Midterm" %>
  </div>

  <%= f.submit "Create", class: "btn btn-success" %> - Next step - Assign Questions 
<% end %>

app/views/assessments/show.html.erb
<h1><%= @assessment.title %></h1>

<ul class='questions-in-assessment'>
  <% @assessment.questions.each do |question| %>
    <li class='list-group-item'>
      <span class='prompt-in-assessment'><%= question.prompt %></span>
      <span class='answer-count-in-assessment'><%= question.answer_count %> answers</span>
    </li>
  <% end %>
</ul>

<%= link_to "Edit questions", assessment_add_questions_path(@assessment), class: 'btn btn-primary' %>

<%= link_to "Export to PDF (NI)", dashboard_path, class: 'btn btn-primary' %>