config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#show', via: :get

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]

  resource :dashboard, only: [:show]

  resources :questions do
    post 'finish' => 'questions#finish'
    resources :answers, only: [:create, :edit, :update, :destroy]
  end

  resources :assessments, only: [:new, :create, :show] do
    get 'add_questions'
    put 'assign_questions'
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  default_scope { order("created_at ASC") }

  validates_presence_of :content
  validates_inclusion_of :correct, in: [true, false]
  validates_presence_of :question_id

  # TODO: Disabled validation because it fails on allowing re-inclusion
  # of a previously deleted answer
  # validates_uniqueness_of :content, scoped_to: :question_id, on: :create
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    question = Question.find_by(id: params[:question_id])
    @answer = question.answers.new(answer_params)
    if @answer.save
      return render @answer
    else
      flash[:errors] = @answer.errors.full_messages
      return render partial: 'shared/errors', status: 203
    end
  end

  def edit
    @answer = Answer.find_by(id: params[:id])
    return render partial: 'edit'
  end

  def update
    @answer = Answer.find_by(id: params[:id])
    if @answer.update_attributes(answer_params)
      return render @answer, status: 200
    else
      flash[:errors] = @answer.errors.full_messages
      return render partial: 'shared/errors', status: 203
    end
  end

  def destroy
    answer = Answer.find_by(id: params[:id])
    if answer.try(:destroy)
      return render nothing: true, status: 200
    else
      return render nothing: true, status: 400
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:content, :correct)
  end
end

app/views/answers/_answer.html.erb
<li class="answer list-group-item">
  <span class='col-xs-1 answer-checkmark'>
    <% if answer.correct %>
      <span class='fa fa-check fa-2x checkmark'></span>
    <% end %>
  </span>

  <span class='answer-content'>
    <%= answer.content %>
  </span>

  <span class='answer-change-links pull-right'>
    <%= link_to edit_question_answer_path(answer.question, answer), method: :get, remote: true, class: 'answer-edit' do %>
      <span class='fa fa-pencil fa-2x'></span>
    <% end %>

    <%= link_to question_answer_path(answer.question, answer), method: :delete, remote: true, class: 'answer-delete' do %>
      <span class='fa fa-remove fa-2x nomark'></span>
    <% end %>
  </span>
</li>

app/views/answers/_edit.html.erb
<h3>Edit question</h3>
<div class='edit-answer-errors'><%= render partial: 'shared/errors' %></div>

<%= form_for :answer, url: question_answer_path(@answer.question, @answer), html: { class: 'edit-answer-form' }, method: :put, remote: true do |f| %>
  <div class='edit-answer'>
    <%= render partial: 'answers/form', locals: { f: f }  %>
  </div>
<% end %>

app/views/answers/_form.html.erb
<span class="form-group">
  <%= f.text_field :content, class: "form-control answer-content" %>
</span>

<span class="answer-checkbox">
  <div class="checkbox checkbox-success checkbox-inline">
    <input type="checkbox" name="answer[correct]">
    <label for="answer[correct]">
        Correct answer?
    </label>
  </div>
</span>

<span class="answer-submit">
  <%= f.submit "Submit", class: 'btn btn-success' %>
</span>

app/views/answers/_new.html.erb
<%= render partial: 'shared/errors' %>

<%= form_for :answer, url: question_answers_path(question), html: { class: 'answer-form' }, remote: true do |f| %>
  <div class='new-answer'>
    <%= render partial: 'answers/form', locals: { f: f } %>
  </div>
<% end %>